---
title: "EDA"
author: "Jiyan Schneider"
output:
  html_document:
    number_sections: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this notebook we will perform the Exploratory data analysis for our
Housing datset.

# Loading and exploring data

Loading the packages.

```{r, message=False, warning=False}
library(knitr)
library(ggplot2)
library(plyr)
library(dplyr)
library(corrplot)
library(caret)
library(gridExtra)
library(scales)
library(Rmisc)
library(ggrepel)
library(randomForest)
library(psych)
library(xgboost)
library(ggthemes)
library(latex2exp)
library(ggplot2)

```

```{r}
theme <- theme_solarized
```

## Reading in the data.
```{r}
df <- read.csv("data/viz_learn_preds.csv")
```


## Data size and structure

```{r}
dim(df)
str(df)
```


Distribution of rent and log apt rent. 
```{r}
p1 <- ggplot(data=df[!is.na(df$apt_rent),], aes(x=apt_rent)) +
        geom_histogram() +
        scale_x_continuous() + ylab("Density") + theme()

p2 <- ggplot(data=df[!is.na(df$apt_rent),], aes(x=log(apt_rent))) +
        geom_histogram(binwidth=0.1) +
        scale_x_continuous() + ylab("Density") + theme()

p3 <-  ggplot(data=df[!is.na(df$apt_rent),], aes(x=b_age)) +
        geom_histogram() +
        scale_x_continuous() + ylab("Count") + xlab("Age of Building") + theme()

p4 <- ggplot(data=df[!is.na(df$apt_rent),], aes(x=b_no_floors)) +
        geom_histogram(binwidth = 1) +
        scale_x_continuous(breaks = seq(0, 60, by=15)) +
        ylab("Count") +
        xlab("# Floors Building") +
        theme()

p5 <- ggplot(data=df[!is.na(df$apt_rent),], aes(x=apt_size)) +
        geom_histogram(binwidth = 5) +
        scale_x_continuous() +
        ylab("Density") +
        xlab("Size") +
        theme()

p6 <- ggplot(data=df[!is.na(df$apt_rent),], aes(x=apt_size)) +
        geom_histogram(binwidth = 5) +
        scale_x_continuous() +
        ylab("Density") +
        xlab(TeX("Size in $m^2$")) +
        theme()

p7 <- ggplot(data=df, aes(x=apt_floor)) +
        geom_histogram(binwidth = 1) +
        scale_x_continuous() +
        ylab("Count") +
        xlab("Floor of apartment") +
        theme()

p8 <- ggplot(data=df[df$apt_admin_price < 50000,], aes(x=apt_admin_price)) +
        geom_histogram() +
        scale_x_continuous() +
        ylab("Density") +
        xlab("Administration Fee (¥)") +
        theme()

p9 <- ggplot(data=df, aes(x=time_to_station)) +
        geom_histogram(binwidth=1) +
        scale_x_continuous() +
        ylab("Density") +
        xlab("Time to station") +
        theme()

```


TODO: apt_style

DONE: apt_admin_price

DONE: apt_floor

DONE: apt_time_to_station

TODO: method

```{r}

ggplot(data=df, aes(x=method)) +
        geom_histogram(stat="count") +
        ylab("Density") +
        xlab("Methods") +
        theme()

```


